/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QLNhanVienController;
import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.NhanVienBep;
import model.NhanVienThuNgan;
import model.QLNhanVienModel;
import model.NhanVien;

/**
 *
 * @author MyPC
 */
public class QLNhanVienView extends javax.swing.JFrame {

    public QLNhanVienModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLNhanVienView.class.getName());
    private ButtonGroup buttonGroup_nvBep;
    private ButtonGroup buttonGroup_nvTn;

    /**
     * Creates new form QLNhanVienView
     */
    public QLNhanVienView() {
        initComponents();
        initView();
    }

    public void initView() {
        this.model = new QLNhanVienModel();
        this.setTitle("QLNV");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        setVisible(true);

        ActionListener ac = new QLNhanVienController(this);

        nvBep_btnSave.addActionListener(ac);
        nvTn_btnSave.addActionListener(ac);
        btn_SaveFile.addActionListener(ac);
        buttonGroup_nvBep = new ButtonGroup();
        buttonGroup_nvBep.add(nvBep_radioBtn_YES);
        buttonGroup_nvBep.add(nvBep_radioBtn_NO);

        buttonGroup_nvTn = new ButtonGroup();
        buttonGroup_nvTn.add(nvTn_radioBtn_YES);
        buttonGroup_nvTn.add(nvTn_radioBtn_NO);

        nvBep_lable_LuongGio_Input3.setText(String.valueOf(NhanVien.LUONG_GIO));
        nvTn_lable_LuongGio_Input4.setText(String.valueOf(NhanVien.LUONG_GIO));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNVThuNgan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNVBep = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nvBep_textField_Name_Input = new javax.swing.JTextField();
        nvBep_textField_ThamNien_Input1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nvBep_textField_QueQuan_Input2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nvBep_textField_Times_Input3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nvBep_lable_LuongGio_Input3 = new javax.swing.JLabel();
        nvBep_btnSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nvTN_textField_Name_Input1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nvTN_textField_ThamNien_Input2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nvTn_textField_QueQuan_Input3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nvTn_textField_Times_Input4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nvTn_lable_LuongGio_Input4 = new javax.swing.JLabel();
        nvTn_btnSave = new javax.swing.JButton();
        btn_SaveFile = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        nvBep_textField_Thuong_Input4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nvBep_radioBtn_NO = new javax.swing.JRadioButton();
        nvBep_radioBtn_YES = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        nvTn_radioBtn_YES = new javax.swing.JRadioButton();
        nvTn_radioBtn_NO = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nhân Viên Thu Ngân");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        tableNVThuNgan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "thâm Niên", "Quê Quán", "Số Giờ Làm", "Biết Ngoại Ngữ", "Lương"
            }
        ));
        jScrollPane1.setViewportView(tableNVThuNgan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 410, 310));

        tableNVBep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Thâm Niên", "Quê Quán", "Số Giờ Làm", "Là Bếp Trưởng", "Thưởng Chức Vụ", "Lương"
            }
        ));
        jScrollPane2.setViewportView(tableNVBep);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 420, 310));

        jLabel3.setText("Nhân Viên Bếp");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 350));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nhân Viên Bếp");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel4.setText("Tên");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        nvBep_textField_Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvBep_textField_Name_InputActionPerformed(evt);
            }
        });
        jPanel2.add(nvBep_textField_Name_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, -1));

        nvBep_textField_ThamNien_Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvBep_textField_ThamNien_Input1ActionPerformed(evt);
            }
        });
        jPanel2.add(nvBep_textField_ThamNien_Input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 140, -1));

        jLabel5.setText("Thâm Niên");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        nvBep_textField_QueQuan_Input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvBep_textField_QueQuan_Input2ActionPerformed(evt);
            }
        });
        jPanel2.add(nvBep_textField_QueQuan_Input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 140, -1));

        jLabel6.setText("Quê Quán");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel7.setText("Số giờ làm");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        nvBep_textField_Times_Input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvBep_textField_Times_Input3ActionPerformed(evt);
            }
        });
        jPanel2.add(nvBep_textField_Times_Input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, -1));

        jLabel8.setText("Lương Giờ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, -1));

        nvBep_lable_LuongGio_Input3.setText("jLabel9");
        jPanel2.add(nvBep_lable_LuongGio_Input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        nvBep_btnSave.setText("Lưu NV Bếp");
        nvBep_btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvBep_btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(nvBep_btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        jLabel9.setText("Nhân Viên Thu Ngân");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jLabel10.setText("Tên");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        nvTN_textField_Name_Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvTN_textField_Name_Input1ActionPerformed(evt);
            }
        });
        jPanel2.add(nvTN_textField_Name_Input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 140, -1));

        jLabel11.setText("Thâm Niên");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        nvTN_textField_ThamNien_Input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvTN_textField_ThamNien_Input2ActionPerformed(evt);
            }
        });
        jPanel2.add(nvTN_textField_ThamNien_Input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 140, -1));

        jLabel12.setText("Quê Quán");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        nvTn_textField_QueQuan_Input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvTn_textField_QueQuan_Input3ActionPerformed(evt);
            }
        });
        jPanel2.add(nvTn_textField_QueQuan_Input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 140, -1));

        jLabel13.setText("Số giờ làm");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        nvTn_textField_Times_Input4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvTn_textField_Times_Input4ActionPerformed(evt);
            }
        });
        jPanel2.add(nvTn_textField_Times_Input4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 140, -1));

        jLabel14.setText("Lương Giờ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 60, -1));

        nvTn_lable_LuongGio_Input4.setText("jLabel9");
        jPanel2.add(nvTn_lable_LuongGio_Input4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        nvTn_btnSave.setText("Lưu NV Thu Ngân");
        jPanel2.add(nvTn_btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        btn_SaveFile.setText("Lưu File");
        jPanel2.add(btn_SaveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 210, 140));

        jLabel15.setText("Bếp Trưởng");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        nvBep_textField_Thuong_Input4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvBep_textField_Thuong_Input4ActionPerformed(evt);
            }
        });
        jPanel2.add(nvBep_textField_Thuong_Input4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, -1));

        jLabel16.setText("Thưởng Chức Vụ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        nvBep_radioBtn_NO.setText("No");
        jPanel2.add(nvBep_radioBtn_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        nvBep_radioBtn_YES.setText("Yes");
        jPanel2.add(nvBep_radioBtn_YES, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel17.setText("Ngoại Ngữ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        nvTn_radioBtn_YES.setText("Yes");
        jPanel2.add(nvTn_radioBtn_YES, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        nvTn_radioBtn_NO.setText("No");
        jPanel2.add(nvTn_radioBtn_NO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 870, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nvBep_textField_Name_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvBep_textField_Name_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvBep_textField_Name_InputActionPerformed

    private void nvBep_textField_ThamNien_Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvBep_textField_ThamNien_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvBep_textField_ThamNien_Input1ActionPerformed

    private void nvBep_textField_QueQuan_Input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvBep_textField_QueQuan_Input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvBep_textField_QueQuan_Input2ActionPerformed

    private void nvBep_textField_Times_Input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvBep_textField_Times_Input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvBep_textField_Times_Input3ActionPerformed

    private void nvTN_textField_Name_Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvTN_textField_Name_Input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvTN_textField_Name_Input1ActionPerformed

    private void nvTN_textField_ThamNien_Input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvTN_textField_ThamNien_Input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvTN_textField_ThamNien_Input2ActionPerformed

    private void nvTn_textField_QueQuan_Input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvTn_textField_QueQuan_Input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvTn_textField_QueQuan_Input3ActionPerformed

    private void nvTn_textField_Times_Input4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvTn_textField_Times_Input4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvTn_textField_Times_Input4ActionPerformed

    private void nvBep_textField_Thuong_Input4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvBep_textField_Thuong_Input4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvBep_textField_Thuong_Input4ActionPerformed

    private void nvBep_btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvBep_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nvBep_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLNhanVienView().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_SaveFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton nvBep_btnSave;
    public javax.swing.JLabel nvBep_lable_LuongGio_Input3;
    public javax.swing.JRadioButton nvBep_radioBtn_NO;
    public javax.swing.JRadioButton nvBep_radioBtn_YES;
    public javax.swing.JTextField nvBep_textField_Name_Input;
    public javax.swing.JTextField nvBep_textField_QueQuan_Input2;
    public javax.swing.JTextField nvBep_textField_ThamNien_Input1;
    public javax.swing.JTextField nvBep_textField_Thuong_Input4;
    public javax.swing.JTextField nvBep_textField_Times_Input3;
    public javax.swing.JTextField nvTN_textField_Name_Input1;
    public javax.swing.JTextField nvTN_textField_ThamNien_Input2;
    public javax.swing.JButton nvTn_btnSave;
    public javax.swing.JLabel nvTn_lable_LuongGio_Input4;
    public javax.swing.JRadioButton nvTn_radioBtn_NO;
    public javax.swing.JRadioButton nvTn_radioBtn_YES;
    public javax.swing.JTextField nvTn_textField_QueQuan_Input3;
    public javax.swing.JTextField nvTn_textField_Times_Input4;
    public javax.swing.JTable tableNVBep;
    public javax.swing.JTable tableNVThuNgan;
    // End of variables declaration//GEN-END:variables

    public void themNhanVienBep(NhanVienBep nvienBep) {
        DefaultTableModel tableModel = (DefaultTableModel) tableNVBep.getModel();
        this.model.insertNVBep(nvienBep);
        tableModel.addRow(new Object[]{nvienBep.getName(),
            nvienBep.getThamnien() + "",
            nvienBep.getQueQuan(),
            nvienBep.getTime(),
            nvienBep.isIsBepTruong() + "",
            nvienBep.getThuongChucVu() + "",
            getLuongNhanVienBep(nvienBep) + ""});
    }

    public void themNhanVienThuNgan(NhanVienThuNgan nhanVienThuNgan) {
        DefaultTableModel tableModel = (DefaultTableModel) tableNVThuNgan.getModel();
        this.model.insertNVThuNgan(nhanVienThuNgan);
        tableModel.addRow(new Object[]{nhanVienThuNgan.getName(),
            nhanVienThuNgan.getThamnien() + "",
            nhanVienThuNgan.getQueQuan(),
            nhanVienThuNgan.getTime(),
            nhanVienThuNgan.isIsBietNgoaiNgu() + "",
            getLuongNhanVienThuNgan(nhanVienThuNgan) + ""});
    }

    public double getLuongNhanVienBep(NhanVienBep nhanVienBep) {
        nhanVienBep.setIsBepTruong(false);
        if (nvBep_radioBtn_YES.isSelected()) {
            nhanVienBep.setIsBepTruong(true);
            return nhanVienBep.tinhLuong();
        } else {
            nvBep_textField_Thuong_Input4.setText("0");
            return nhanVienBep.tinhLuong();
        }
    }

    public double getLuongNhanVienThuNgan(NhanVienThuNgan nhanVienThuNgan) {
        nhanVienThuNgan.setIsBietNgoaiNgu(false);
        if (nvTn_radioBtn_YES.isSelected()) {
            nhanVienThuNgan.setIsBietNgoaiNgu(true);
            return nhanVienThuNgan.tinhLuong();
        } else {

            return nhanVienThuNgan.tinhLuong();
        }
    }

    public void clearNhanVienBep() {
        nvBep_textField_Name_Input.setText("");
        nvBep_textField_ThamNien_Input1.setText("");
        nvBep_textField_QueQuan_Input2.setText("");
        nvBep_textField_Times_Input3.setText("");
        nvBep_textField_Thuong_Input4.setText("");
        buttonGroup_nvBep.clearSelection();
    }

    public void clearNhanVienThuNgan() {
        nvTN_textField_Name_Input1.setText("");
        nvTN_textField_ThamNien_Input2.setText("");
        nvTn_textField_QueQuan_Input3.setText("");
        nvTn_textField_Times_Input4.setText("");
        buttonGroup_nvTn.clearSelection();
    }

    public void luuFile() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("nhanvien.txt"))) {
            for (NhanVien nv : model.listNhanVienBep) {
                bw.write("Nhan Vien Bep: ");
                bw.write(nv.toString());
                bw.newLine();
            }

            for (NhanVien nv : model.listNhanVienTn) {
                bw.write("Nhan Vien Thu Ngan: ");
                bw.write(nv.toString());
                bw.newLine();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi khi lưu file: " + e.getMessage());
        }
    }

    public QLNhanVienView(QLNhanVienModel model, ButtonGroup buttonGroup_nvBep, JButton btn_SaveFile, JLabel jLabel1, JLabel jLabel10, JLabel jLabel11, JLabel jLabel12, JLabel jLabel13, JLabel jLabel14, JLabel jLabel15, JLabel jLabel16, JLabel jLabel17, JLabel jLabel2, JLabel jLabel3, JLabel jLabel4, JLabel jLabel5, JLabel jLabel6, JLabel jLabel7, JLabel jLabel8, JLabel jLabel9, JPanel jPanel1, JPanel jPanel2, JScrollPane jScrollPane1, JScrollPane jScrollPane2, JButton nvBep_btnSave, JLabel nvBep_lable_LuongGio_Input3, JRadioButton nvBep_radioBtn_NO, JRadioButton nvBep_radioBtn_YES, JTextField nvBep_textField_Name_Input, JTextField nvBep_textField_QueQuan_Input2, JTextField nvBep_textField_ThamNien_Input1, JTextField nvBep_textField_Thuong_Input4, JTextField nvBep_textField_Times_Input3, JTextField nvTN_textField_Name_Input1, JTextField nvTN_textField_ThamNien_Input2, JButton nvTn_btnSave, JLabel nvTn_lable_LuongGio_Input4, JRadioButton nvTn_radioBtn_NO, JRadioButton nvTn_radioBtn_YES, JTextField nvTn_textField_QueQuan_Input3, JTextField nvTn_textField_Times_Input4, JTable tableNVBep, JTable tableNVThuNgan) throws HeadlessException {
        this.model = model;
        this.buttonGroup_nvBep = buttonGroup_nvBep;
        this.btn_SaveFile = btn_SaveFile;
        this.jLabel1 = jLabel1;
        this.jLabel10 = jLabel10;
        this.jLabel11 = jLabel11;
        this.jLabel12 = jLabel12;
        this.jLabel13 = jLabel13;
        this.jLabel14 = jLabel14;
        this.jLabel15 = jLabel15;
        this.jLabel16 = jLabel16;
        this.jLabel17 = jLabel17;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jLabel6 = jLabel6;
        this.jLabel7 = jLabel7;
        this.jLabel8 = jLabel8;
        this.jLabel9 = jLabel9;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jScrollPane1 = jScrollPane1;
        this.jScrollPane2 = jScrollPane2;
        this.nvBep_btnSave = nvBep_btnSave;
        this.nvBep_lable_LuongGio_Input3 = nvBep_lable_LuongGio_Input3;
        this.nvBep_radioBtn_NO = nvBep_radioBtn_NO;
        this.nvBep_radioBtn_YES = nvBep_radioBtn_YES;
        this.nvBep_textField_Name_Input = nvBep_textField_Name_Input;
        this.nvBep_textField_QueQuan_Input2 = nvBep_textField_QueQuan_Input2;
        this.nvBep_textField_ThamNien_Input1 = nvBep_textField_ThamNien_Input1;
        this.nvBep_textField_Thuong_Input4 = nvBep_textField_Thuong_Input4;
        this.nvBep_textField_Times_Input3 = nvBep_textField_Times_Input3;
        this.nvTN_textField_Name_Input1 = nvTN_textField_Name_Input1;
        this.nvTN_textField_ThamNien_Input2 = nvTN_textField_ThamNien_Input2;
        this.nvTn_btnSave = nvTn_btnSave;
        this.nvTn_lable_LuongGio_Input4 = nvTn_lable_LuongGio_Input4;
        this.nvTn_radioBtn_NO = nvTn_radioBtn_NO;
        this.nvTn_radioBtn_YES = nvTn_radioBtn_YES;
        this.nvTn_textField_QueQuan_Input3 = nvTn_textField_QueQuan_Input3;
        this.nvTn_textField_Times_Input4 = nvTn_textField_Times_Input4;
        this.tableNVBep = tableNVBep;
        this.tableNVThuNgan = tableNVThuNgan;
    }

}
