/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QLNhaHangController;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DoUong;
import model.MonAnThem;
import model.QLNhaHangModel;

/**
 *
 * @author MyPC
 */
public class QLNhaHangView extends javax.swing.JFrame {

    public QLNhaHangModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLNhaHangView.class.getName());

    /**
     * Creates new form QLNhaHangView
     */
    public QLNhaHangView() {
        model = new QLNhaHangModel();
        initComponents();
        initSetUp();
    }

    public void initSetUp() {
        this.setTitle("QL nha hang");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

        ActionListener ac = new QLNhaHangController(this);

        this.model.docFile("C:\\Users\\MyPC\\Documents\\NetBeansProjects\\thi2-2\\mathang.txt");
        for (MonAnThem listMonAnThem : model.listMonAnThems) {
            themMonAnThem(listMonAnThem);
        }
        for (DoUong doUong : model.listDoUong) {
            themDoUong(doUong);
        }
        System.out.println("Mon an them: " + model.listMonAnThems.size());
        System.out.println("Do uong: " + model.listDoUong.size());

        this.btn_Find.addActionListener(ac);
        this.btn_Sort.addActionListener(ac);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField_TimKiemCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_Find = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_Sort = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_MonAnThem = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_DoUong = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sắp Xếp Giá");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        jPanel1.add(textField_TimKiemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 150, -1));

        jLabel2.setText("Mã Tìm Kiếm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 50));

        btn_Find.setText("Tìm Kiếm");
        jPanel1.add(btn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 100, -1));

        jLabel3.setText("Tìm Kiếm Thông Tin Các Mặt Hàng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 10));

        btn_Sort.setText("Sắp Xếp");
        jPanel1.add(btn_Sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 790, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Món Ăn Thêm");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, 30));

        table_MonAnThem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Mã MH", "Số Lượng", "Giá Vốn", "Trình Bày", "Giá Menu"
            }
        ));
        jScrollPane1.setViewportView(table_MonAnThem);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 380));

        table_DoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Mã MH", "Số Lượng", "Giá Vốn", "Nóng", "Giá Menu"
            }
        ));
        jScrollPane2.setViewportView(table_DoUong);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 370, 380));

        jLabel5.setText("Đồ Uống");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 120, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLNhaHangView().setVisible(true));
    }

    public void themMonAnThem(MonAnThem mat) {
        DefaultTableModel tableModel = (DefaultTableModel) table_MonAnThem.getModel();
        tableModel.addRow(new Object[]{
            mat.getName(),
            mat.getCode(),
            mat.getAmount(),
            mat.getGiaVon(),
            mat.isCanTrinhBay(),
            mat.tinhGiaMenu()});
    }

    public void themDoUong(DoUong doUong) {
        DefaultTableModel tableModel = (DefaultTableModel) table_DoUong.getModel();
        tableModel.addRow(new Object[]{
            doUong.getName(),
            doUong.getCode(),
            doUong.getAmount(),
            doUong.getGiaVon(),
            doUong.isIsHotDrink(),
            doUong.tinhGiaMenu()});
    }

    public void timKiem(String code) {
        int index_row = 0;
        for (MonAnThem listMonAnThem : model.listMonAnThems) {
            if (listMonAnThem.getCode().equals(code)) {
                
                JOptionPane.showMessageDialog(this,
                        listMonAnThem.toString(),
                        "Tim Thay Mat Hang",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            index_row++;
        }
        for (DoUong doUong : model.listDoUong) {
            if (doUong.getCode().equals(code)) {
                JOptionPane.showMessageDialog(this,
                        doUong.toString(),
                        "Tim Thay Mat Hang",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Khong Tim Thay Mat Hang");
    }

    public void sapXep() {

        model.listMonAnThems.sort(
                (a, b) -> Double.compare(b.tinhGiaMenu(), a.tinhGiaMenu())
        );

        model.listDoUong.sort(
                (a, b) -> Double.compare(b.tinhGiaMenu(), a.tinhGiaMenu())
        );


        DefaultTableModel modelMonAn
                = (DefaultTableModel) table_MonAnThem.getModel();
        modelMonAn.setRowCount(0);

        DefaultTableModel modelDoUong
                = (DefaultTableModel) table_DoUong.getModel();
        modelDoUong.setRowCount(0);
        
        for (MonAnThem m : model.listMonAnThems) {
            themMonAnThem(m);
        }

        for (DoUong d : model.listDoUong) {
            themDoUong(d);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Find;
    public javax.swing.JButton btn_Sort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable table_DoUong;
    public javax.swing.JTable table_MonAnThem;
    public javax.swing.JTextField textField_TimKiemCode;
    // End of variables declaration//GEN-END:variables
}
