/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QLCBController;
import exception.InvalidNumberException;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import model.QLCanBoModel;
import model.QuanLy;

/**
 *
 * @author MyPC
 */
public class QLCanBoView extends javax.swing.JFrame {

    public QLCanBoModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLCanBoView.class.getName());

    /**
     * Creates new form QLCanBoView
     */
    public QLCanBoView() {

        model = new QLCanBoModel();
        initComponents();
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nv = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_ql = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_name_input_nv = new javax.swing.JTextField();
        tf_yearBirth_input_nv1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_address_input_nv2 = new javax.swing.JTextField();
        tf_hesoluong_input_nv3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_major_input_nv4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radiobtn_sex_nu_input_nv = new javax.swing.JRadioButton();
        radiobtn_sex_nam_input_nv = new javax.swing.JRadioButton();
        btnSave_nv = new javax.swing.JButton();
        btnSaveFile = new javax.swing.JButton();
        tf_hsChucVu_input_ql = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_hesoluong_input_ql = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_address_input_ql = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        radiobtn_sex_nu_input_ql = new javax.swing.JRadioButton();
        radiobtn_sex_nam_input_ql = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        tf_yearBirth_input_ql = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_name_input_ql = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSave_ql1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Danh Sách Nhân Viên");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        table_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Năm Sinh", "Giới Tính", "Địa Chỉ", "HSố lương", "Ngành ĐT", "Lương"
            }
        ));
        jScrollPane1.setViewportView(table_nv);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 300));

        table_ql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Năm Sinh", "Giới Tính", "Địa Chỉ", "HSố lương", "HSố CVụ", "Lương"
            }
        ));
        jScrollPane2.setViewportView(table_ql);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 480, 300));

        jLabel2.setText("Danh Sách Quản Lý");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 970, 340));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Họ Tên");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        jLabel4.setText("Nhân Viên");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));
        jPanel3.add(tf_name_input_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        tf_yearBirth_input_nv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_yearBirth_input_nv1ActionPerformed(evt);
            }
        });
        jPanel3.add(tf_yearBirth_input_nv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, -1));

        jLabel5.setText("Năm Sinh");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, -1));

        jLabel6.setText("Giới Tính");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        tf_address_input_nv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_address_input_nv2ActionPerformed(evt);
            }
        });
        jPanel3.add(tf_address_input_nv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, -1));

        tf_hesoluong_input_nv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hesoluong_input_nv3ActionPerformed(evt);
            }
        });
        jPanel3.add(tf_hesoluong_input_nv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));

        jLabel7.setText("Hệ Số Lương");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        tf_major_input_nv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_major_input_nv4ActionPerformed(evt);
            }
        });
        jPanel3.add(tf_major_input_nv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, -1));

        jLabel8.setText("Ngành Đào Tạo");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        jLabel9.setText("Địa Chỉ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, -1));

        radiobtn_sex_nu_input_nv.setText("Nữ");
        radiobtn_sex_nu_input_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_sex_nu_input_nvActionPerformed(evt);
            }
        });
        jPanel3.add(radiobtn_sex_nu_input_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        radiobtn_sex_nam_input_nv.setText("Nam");
        radiobtn_sex_nam_input_nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_sex_nam_input_nvActionPerformed(evt);
            }
        });
        jPanel3.add(radiobtn_sex_nam_input_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btnSave_nv.setText("Lưu NV");
        jPanel3.add(btnSave_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, -1));

        btnSaveFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSaveFile.setText("Lưu File");
        jPanel3.add(btnSaveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 190, 140));

        tf_hsChucVu_input_ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hsChucVu_input_qlActionPerformed(evt);
            }
        });
        jPanel3.add(tf_hsChucVu_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 140, -1));

        jLabel10.setText("Hệ Số Chức Vụ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 80, -1));

        tf_hesoluong_input_ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hesoluong_input_qlActionPerformed(evt);
            }
        });
        jPanel3.add(tf_hesoluong_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 140, -1));

        jLabel11.setText("Hệ Số Lương");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, -1));

        tf_address_input_ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_address_input_qlActionPerformed(evt);
            }
        });
        jPanel3.add(tf_address_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 140, -1));

        jLabel12.setText("Địa Chỉ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 50, -1));

        radiobtn_sex_nu_input_ql.setText("Nữ");
        radiobtn_sex_nu_input_ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_sex_nu_input_qlActionPerformed(evt);
            }
        });
        jPanel3.add(radiobtn_sex_nu_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        radiobtn_sex_nam_input_ql.setText("Nam");
        radiobtn_sex_nam_input_ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtn_sex_nam_input_qlActionPerformed(evt);
            }
        });
        jPanel3.add(radiobtn_sex_nam_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        jLabel13.setText("Giới Tính");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 50, -1));

        tf_yearBirth_input_ql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_yearBirth_input_qlActionPerformed(evt);
            }
        });
        jPanel3.add(tf_yearBirth_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 140, -1));

        jLabel14.setText("Năm Sinh");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 50, -1));
        jPanel3.add(tf_name_input_ql, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 140, 30));

        jLabel15.setText("Họ Tên");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 50, -1));

        jLabel16.setText("Quản Lý");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        btnSave_ql1.setText("Lưu QL");
        jPanel3.add(btnSave_ql1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 980, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_yearBirth_input_nv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_yearBirth_input_nv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_yearBirth_input_nv1ActionPerformed

    private void tf_address_input_nv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_address_input_nv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_address_input_nv2ActionPerformed

    private void tf_hesoluong_input_nv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hesoluong_input_nv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hesoluong_input_nv3ActionPerformed

    private void tf_major_input_nv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_major_input_nv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_major_input_nv4ActionPerformed

    private void radiobtn_sex_nu_input_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_sex_nu_input_nvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_sex_nu_input_nvActionPerformed

    private void radiobtn_sex_nam_input_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_sex_nam_input_nvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_sex_nam_input_nvActionPerformed

    private void tf_hsChucVu_input_qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hsChucVu_input_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hsChucVu_input_qlActionPerformed

    private void tf_hesoluong_input_qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hesoluong_input_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hesoluong_input_qlActionPerformed

    private void tf_address_input_qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_address_input_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_address_input_qlActionPerformed

    private void radiobtn_sex_nu_input_qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_sex_nu_input_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_sex_nu_input_qlActionPerformed

    private void radiobtn_sex_nam_input_qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtn_sex_nam_input_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtn_sex_nam_input_qlActionPerformed

    private void tf_yearBirth_input_qlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_yearBirth_input_qlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_yearBirth_input_qlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLCanBoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSaveFile;
    public javax.swing.JButton btnSave_nv;
    public javax.swing.JButton btnSave_ql1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton radiobtn_sex_nam_input_nv;
    public javax.swing.JRadioButton radiobtn_sex_nam_input_ql;
    public javax.swing.JRadioButton radiobtn_sex_nu_input_nv;
    public javax.swing.JRadioButton radiobtn_sex_nu_input_ql;
    public javax.swing.JTable table_nv;
    public javax.swing.JTable table_ql;
    public javax.swing.JTextField tf_address_input_nv2;
    public javax.swing.JTextField tf_address_input_ql;
    public javax.swing.JTextField tf_hesoluong_input_nv3;
    public javax.swing.JTextField tf_hesoluong_input_ql;
    public javax.swing.JTextField tf_hsChucVu_input_ql;
    public javax.swing.JTextField tf_major_input_nv4;
    public javax.swing.JTextField tf_name_input_nv;
    public javax.swing.JTextField tf_name_input_ql;
    public javax.swing.JTextField tf_yearBirth_input_nv1;
    public javax.swing.JTextField tf_yearBirth_input_ql;
    // End of variables declaration//GEN-END:variables

    public void initView() {
        setTitle("QL Can Bo");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        ActionListener ac = new QLCBController(this);

        ButtonGroup buttonGroup_Sex_nv = new ButtonGroup();
        buttonGroup_Sex_nv.add(radiobtn_sex_nam_input_nv);
        buttonGroup_Sex_nv.add(radiobtn_sex_nu_input_nv);
        buttonGroup_Sex_nv.clearSelection();

        ButtonGroup buttonGroup_Sex_ql = new ButtonGroup();
        buttonGroup_Sex_ql.add(radiobtn_sex_nam_input_ql);
        buttonGroup_Sex_ql.add(radiobtn_sex_nu_input_ql);
        buttonGroup_Sex_ql.clearSelection();

        btnSave_nv.addActionListener(ac);
        btnSave_ql1.addActionListener(ac);
        btnSaveFile.addActionListener(ac);

        setVisible(true);
    }

    public void getNhanVien() throws InvalidNumberException {
        String name = tf_name_input_nv.getText();

        int yearBirth = parsePositiveInt(tf_yearBirth_input_nv1.getText(), "Nam Sinh");

        boolean sex = false;

        if (radiobtn_sex_nam_input_nv.isSelected()) {
            sex = true;
        }

        String address = tf_address_input_nv2.getText();

        double hsl = parsePositiveDouble(tf_hesoluong_input_nv3.getText(), "Hệ Số Lương");
        String major = tf_major_input_nv4.getText();
        NhanVien nv = new NhanVien(major, name, yearBirth, sex, address, hsl);

        themNV(nv);
    }

    public void getQuanLy() throws InvalidNumberException {
        String name = tf_name_input_ql.getText();

        int yearBirth = parsePositiveInt(tf_yearBirth_input_ql.getText(), "Nam Sinh");

        boolean sex = false;

        if (radiobtn_sex_nam_input_ql.isSelected()) {
            sex = true;
        }

        String address = tf_address_input_ql.getText();

        double hsl = parsePositiveDouble(tf_hesoluong_input_ql.getText(), "Hệ Số Lương");
        double hsChuVu = parsePositiveDoubleHSCV(tf_hsChucVu_input_ql.getText(), "Hệ Số chức vụ");
        QuanLy ql = new QuanLy(hsChuVu, name, yearBirth, sex, address, hsl);
        themQL(ql);
    }

    public void themNV(NhanVien nv) {
        DefaultTableModel tableModel = (DefaultTableModel) table_nv.getModel();
        model.addNhanVien(nv);

        tableModel.addRow(new Object[]{nv.getName(),
            nv.getDateOfBirth(),
            nv.getSexString(),
            nv.getAddress(),
            nv.getHeSoLuonng(),
            nv.getMajor(),
            nv.tinhLuong()});
    }

    public void themQL(QuanLy ql) {
        DefaultTableModel tableModel = (DefaultTableModel) table_ql.getModel();
        model.addQuanLy(ql);

        tableModel.addRow(new Object[]{ql.getName(),
            ql.getDateOfBirth(),
            ql.getSexString(),
            ql.getAddress(),
            ql.getHeSoLuonng(),
            ql.getHsChucVu(),
            ql.tinhLuong()});
    }

    private int parsePositiveInt(String input, String fieldName)
            throws InvalidNumberException {

        if (input == null || input.trim().isEmpty()) {
            throw new InvalidNumberException(fieldName + " không được để trống");
        }

        try {
            int value = Integer.parseInt(input.trim());
            if (value <= 0) {
                throw new InvalidNumberException(fieldName + " phải là số dương");
            }
            return value;
        } catch (NumberFormatException e) {
            throw new InvalidNumberException(fieldName + " phải là số nguyên");
        }
    }

    private double parsePositiveDoubleHSCV(String input, String fieldName)
            throws InvalidNumberException {

        if (input == null || input.trim().isEmpty()) {
            throw new InvalidNumberException(fieldName + " không được để trống");
        }

        try {
            double value = Double.parseDouble(input.trim());
            if (value <= 0 || value > 1) {
                throw new InvalidNumberException(fieldName + " phải là số dương và nằm trong khoảng (0->1)");
            }
            return value;
        } catch (NumberFormatException e) {
            throw new InvalidNumberException(fieldName + " phải là số nguyên");
        }
    }

    private double parsePositiveDouble(String input, String fieldName)
            throws InvalidNumberException {

        if (input == null || input.trim().isEmpty()) {
            throw new InvalidNumberException(fieldName + " không được để trống");
        }

        try {
            double value = Double.parseDouble(input.trim());
            if (value <= 0) {
                throw new InvalidNumberException(fieldName + " phải là số dương");
            }
            return value;
        } catch (NumberFormatException e) {
            throw new InvalidNumberException(fieldName + " phải là số nguyên");
        }
    }

    public void luuFile() throws Exception {
    try (BufferedWriter bw = new BufferedWriter(new FileWriter("canbo.txt"))) {

        for (QuanLy ql : model.listQLs) {
            bw.write("" + ql);
            bw.newLine();
        }

        for (NhanVien nv : model.listNVs) {
            bw.write("" + nv);
            bw.newLine();
        }
    }
}
}
