/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QLTKController;
import exception.InValidInputExecption;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.QLTKModel;
import model.TaiKhoanThanhToan;
import model.TaiKhoanTietKiem;

/**
 *
 * @author MyPC
 */
public class QLTKView extends javax.swing.JFrame {

    public QLTKModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLTKView.class.getName());

    /**
     * Creates new form QLTKView
     */
    public QLTKView() {
        model = new QLTKModel();
        initComponents();
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_TKTK = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_TKTT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_ThongKe = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lable_ThongKeSoDu = new javax.swing.JLabel();
        btn_luuFile = new javax.swing.JButton();
        btn_ThongKe1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_code_TKTT = new javax.swing.JTextField();
        tf_own_TKTT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_soDu_TKTT = new javax.swing.JTextField();
        tf_loaiThe_TKTT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_SoGiaoDich_TKTT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_save_TKTT = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_code_TKTK1 = new javax.swing.JTextField();
        tf_own_TKTK1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_soDu_TKTK1 = new javax.swing.JTextField();
        tf_laiSuat_TKTK2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_kyHan_TKTK3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btn_save_TKTK1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Danh Sách TK Tiết Kiệm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        table_TKTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã TK", "Chủ TK", "Số Dư", "Lãi Suất", "Kỳ Hạn"
            }
        ));
        jScrollPane1.setViewportView(table_TKTK);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 300));

        table_TKTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã TK", "Chủ TK", "Số Dư", "Loại Thẻ", "Số GDich"
            }
        ));
        jScrollPane2.setViewportView(table_TKTT);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 320, 300));

        jLabel2.setText("Danh Sách TK Thanh Toán");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 340));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã TK", "Chủ TK", "Số Dư", "Loại Thẻ", "Số GDich"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 320, 300));

        jLabel3.setText("Danh Sách TK Thanh Toán");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel4.setText("Tổng Số Dư:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 516, 80, 20));

        table_ThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã TK", "Chủ TK", "Tài Khoản", "Số Dư"
            }
        ));
        jScrollPane4.setViewportView(table_ThongKe);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 290, 440));

        jLabel5.setText("Bảng Thống Kê Số Dư");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, -1));

        lable_ThongKeSoDu.setText("xxx.xxx.xxx.xxx");
        jPanel2.add(lable_ThongKeSoDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 516, 90, 20));

        btn_luuFile.setText("Lưu File");
        jPanel2.add(btn_luuFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 220, -1));

        btn_ThongKe1.setText("Thống Kê");
        jPanel2.add(btn_ThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 220, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 310, 580));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 970, 200));

        jLabel6.setText("Nhập thông tin TKTT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel7.setText("Mã TK");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel4.add(tf_code_TKTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));
        jPanel4.add(tf_own_TKTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, -1));

        jLabel8.setText("Chủ TK");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel9.setText("Số Dư");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel4.add(tf_soDu_TKTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, -1));
        jPanel4.add(tf_loaiThe_TKTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jLabel10.setText("Loại Thẻ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel4.add(tf_SoGiaoDich_TKTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));

        jLabel11.setText("Số Giao Dịch");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btn_save_TKTT.setText("Lưu TKTT");
        jPanel4.add(btn_save_TKTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 330, 230));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 970, 200));

        jLabel12.setText("Nhập thông tin TKTK");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel13.setText("Mã TK");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel6.add(tf_code_TKTK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));
        jPanel6.add(tf_own_TKTK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 170, -1));

        jLabel14.setText("Chủ TK");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel15.setText("Số Dư");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel6.add(tf_soDu_TKTK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, -1));
        jPanel6.add(tf_laiSuat_TKTK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jLabel16.setText("Lãi Suất");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel6.add(tf_kyHan_TKTK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));

        jLabel17.setText("Kỳ hạn");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        btn_save_TKTK1.setText("Lưu TKTK");
        jPanel6.add(btn_save_TKTK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 330, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLTKView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_ThongKe1;
    public javax.swing.JButton btn_luuFile;
    public javax.swing.JButton btn_save_TKTK1;
    public javax.swing.JButton btn_save_TKTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    public javax.swing.JLabel lable_ThongKeSoDu;
    public javax.swing.JTable table_TKTK;
    public javax.swing.JTable table_TKTT;
    public javax.swing.JTable table_ThongKe;
    public javax.swing.JTextField tf_SoGiaoDich_TKTT;
    public javax.swing.JTextField tf_code_TKTK1;
    public javax.swing.JTextField tf_code_TKTT;
    public javax.swing.JTextField tf_kyHan_TKTK3;
    public javax.swing.JTextField tf_laiSuat_TKTK2;
    public javax.swing.JTextField tf_loaiThe_TKTT;
    public javax.swing.JTextField tf_own_TKTK1;
    public javax.swing.JTextField tf_own_TKTT;
    public javax.swing.JTextField tf_soDu_TKTK1;
    public javax.swing.JTextField tf_soDu_TKTT;
    // End of variables declaration//GEN-END:variables

    public void initView() {
        setTitle("Quan ly tai khoan");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        ActionListener ac = new QLTKController(this);
        btn_save_TKTK1.addActionListener(ac);
        btn_save_TKTT.addActionListener(ac);
        btn_luuFile.addActionListener(ac);
        btn_ThongKe1.addActionListener(ac);

        setVisible(true);
    }

    public void themTKTK(TaiKhoanTietKiem tktk) throws InValidInputExecption {
        model.addTKTK(tktk);
    }

    public void themTKTT(TaiKhoanThanhToan tktt) throws InValidInputExecption {
        model.addTKTT(tktt);
    }

    public void showTKTK() throws InValidInputExecption {
        String maTk = tf_code_TKTK1.getText();
        String chuTk = tf_own_TKTK1.getText();
        double soDu = parseDoubleStrix(tf_soDu_TKTK1.getText(), "Số Dư");
        double laiSuat = parseLaiSuatDouble(tf_laiSuat_TKTK2.getText());
        double kyHan = parseDoubleStrix(tf_kyHan_TKTK3.getText(), "Kỳ Hạn");

        TaiKhoanTietKiem tktk = new TaiKhoanTietKiem(laiSuat, kyHan, maTk, chuTk, soDu);
        themTKTK(tktk);

        DefaultTableModel tableModel = (DefaultTableModel) table_TKTK.getModel();

        tableModel.addRow(new Object[]{
            tktk.getMaTk(),
            tktk.getTenChuTk(),
            tktk.getSoDu(),
            tktk.getLaiSuat(),
            tktk.getKiHan()});

    }

    public void showTKTT() throws InValidInputExecption {
        String maTk = tf_code_TKTT.getText();
        String chuTk = tf_own_TKTT.getText();
        double soDu = parseDoubleStrix(tf_soDu_TKTT.getText(), "Số Dư");
        String loaiThe = tf_loaiThe_TKTT.getText();
        double soGiaoDich = parseDoubleStrix(tf_SoGiaoDich_TKTT.getText(), "Số Giao Dịch");

        TaiKhoanThanhToan tktt = new TaiKhoanThanhToan(loaiThe, soGiaoDich, maTk, chuTk, soDu);
        themTKTT(tktt);
        DefaultTableModel tableModel = (DefaultTableModel) table_TKTT.getModel();

        tableModel.addRow(new Object[]{
            tktt.getMaTk(),
            tktt.getTenChuTk(),
            tktt.getSoDu(),
            tktt.getLoaiThe(),
            tktt.getSoGiaoDich()});

    }

    public void showThongKe() {
        DefaultTableModel tableModel = (DefaultTableModel) table_ThongKe.getModel();
        tableModel.setRowCount(0);
        double tongSoDU = 0;
        for (TaiKhoanTietKiem taiKhoanTietKiem : model.listTKTK) {
            tableModel.addRow(new Object[]{taiKhoanTietKiem.getMaTk(),
                taiKhoanTietKiem.getTenChuTk(),
                "Tiết Kiệm",
                taiKhoanTietKiem.getSoDu()});
            tongSoDU += taiKhoanTietKiem.getSoDu();
        }
        for (TaiKhoanThanhToan tktt : model.listTKTT) {
            tableModel.addRow(new Object[]{tktt.getMaTk(),
                tktt.getTenChuTk(),
                "Thanh Toán",
                tktt.getSoDu()});
            tongSoDU += tktt.getSoDu();
        }

        lable_ThongKeSoDu.setText(tongSoDU + "");
    }

    
    public void luuFile(String path){
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(path))) {
            for (TaiKhoanTietKiem taiKhoanTietKiem : model.listTKTK) {
                bw.write(taiKhoanTietKiem.toString());
                bw.newLine();
                bw.flush();
            }
            for (TaiKhoanThanhToan taiKhoanThanhToan : model.listTKTT) {
                bw.write(taiKhoanThanhToan.toString());
                bw.newLine();
                bw.flush();
            }
            
            JOptionPane.showMessageDialog(this, "LUU FILE THANH CONG", "FILE", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "LOI LUU FILE ???", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    

    public double parseLaiSuatDouble(String input) throws InValidInputExecption {
        if (input.trim().isEmpty() || input == null) {
            throw new InValidInputExecption("Lãi Suất không được để trống");
        }

        try {
            double value = Double.parseDouble(input.trim());
            if (value < 0 || value > 1) {
                throw new InValidInputExecption("Lãi Suất không được âm và không được quá 100%/năm");
            }
            return value;
        } catch (NumberFormatException e) {
            throw new InValidInputExecption("Lãi Suất phải nhập số");
        }
    }

    public double parseDoubleStrix(String input, String name) throws InValidInputExecption {
        if (input.trim().isEmpty() || input == null) {
            throw new InValidInputExecption(name + " không được để trống");
        }

        try {
            double value = Double.parseDouble(input.trim());
            if (value < 0) {
                throw new InValidInputExecption(name + " không được âm");
            }
            return value;
        } catch (NumberFormatException e) {
            throw new InValidInputExecption(name + " phải nhập số");
        }
    }

}
