/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QLCuaHangController;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DienThoai;
import model.MayTinhBang;
import model.QLCuaHangModel;

/**
 *
 * @author MyPC
 */
public class QLCuaHangView extends javax.swing.JFrame {

    public QLCuaHangModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLCuaHangView.class.getName());

    /**
     * Creates new form QLCuaHangView
     */
    public QLCuaHangView() throws Exception {
        model = new QLCuaHangModel();
        initComponents();
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Phone = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Tablet = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_code_timKiem = new javax.swing.JTextField();
        btn_Sort = new javax.swing.JButton();
        btn_Find = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_Phone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Mã SP", "Giá Nhập", "Giá Bán", "Giá SimGhép", "Lợi Nhuận"
            }
        ));
        jScrollPane2.setViewportView(table_Phone);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 430, 290));

        table_Tablet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Mã SP", "Giá Nhập", "Giá Bán", "KT Màn Hình", "Lợi Nhuận"
            }
        ));
        jScrollPane3.setViewportView(table_Tablet);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 430, 290));

        jLabel2.setText("Danh Sach Máy Tính Bảng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel3.setText("Danh Sách Điện Thoại");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 880, 330));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sắp Xếp Nhanh");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));
        jPanel2.add(tf_code_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, -1));

        btn_Sort.setText("Sắp Xếp");
        jPanel2.add(btn_Sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 100, -1));

        btn_Find.setText("Tìm Kiếm");
        jPanel2.add(btn_Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, -1));

        jLabel4.setText("Tìm Kiếm Nhanh Bằng Mã SP");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 160, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 880, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new QLCuaHangView().setVisible(true);
            } catch (Exception ex) {
                System.getLogger(QLCuaHangView.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Find;
    public javax.swing.JButton btn_Sort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable table_Phone;
    public javax.swing.JTable table_Tablet;
    public javax.swing.JTextField tf_code_timKiem;
    // End of variables declaration//GEN-END:variables
    public void initView() throws Exception {
        setTitle("Quan Ly Cua Hang");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        ActionListener ac = new QLCuaHangController(this);

        btn_Find.addActionListener(ac);
        btn_Sort.addActionListener(ac);
        model.docFile("hanghoa.txt");

        for (DienThoai dienThoai : model.listPhone) {
            showPhone(dienThoai);
        }
        for (MayTinhBang mayTinhBang : model.listTablet) {
            showTablet(mayTinhBang);
        }
        setVisible(true);
    }

    public void showPhone(DienThoai dt) {
        DefaultTableModel tableModel = (DefaultTableModel) table_Phone.getModel();
        tableModel.addRow(new Object[]{
            dt.getName(),
            dt.getCode(),
            dt.getGiaNhap(),
            dt.getGiaBan(),
            dt.getGiaSimGhep(),
            dt.getloiNhuan()});
    }

    public void showTablet(MayTinhBang mtb) {
        DefaultTableModel tableModel = (DefaultTableModel) table_Tablet.getModel();
        tableModel.addRow(new Object[]{
            mtb.getName(),
            mtb.getCode(),
            mtb.getGiaNhap(),
            mtb.getGiaBan(),
            mtb.getScreenSize(),
            mtb.getloiNhuan()});
    }

    public void timKiem(String code) {
        for (DienThoai dienThoai : model.listPhone) {
            if (code.equals(dienThoai.getCode())) {
                JOptionPane.showMessageDialog(this,
                        "Tim Thay San Pham: " + dienThoai.toString(),
                        "Tim Kiem SP",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        for (MayTinhBang mayTinhBang : model.listTablet) {
            if (code.equals(mayTinhBang.getCode())) {
                JOptionPane.showMessageDialog(this,
                        "Tim Thay SP: " + mayTinhBang.toString(),
                        "Tim Kiem SP",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }

        }
        JOptionPane.showMessageDialog(this,
                "Khong Tim Thay SP Nao voi ma Code " + code,
                "Tim Kiem SP",
                JOptionPane.INFORMATION_MESSAGE);
    }

    public void timKiemSelectRow(String code) {
        for (int i = 0; i < model.listPhone.size(); i++) {
            DienThoai dt = model.listPhone.get(i);

            if (code.equals(dt.getCode())) {
                // Select row
                table_Phone.setRowSelectionInterval(i, i);

                // Scroll tới row được chọn
                table_Phone.scrollRectToVisible(
                        table_Phone.getCellRect(i, 0, true)
                );
                JOptionPane.showMessageDialog(this,
                        "Tìm thấy sản phẩm:\n" + dt,
                        "Tìm kiếm SP",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        for (int i = 0; i < model.listTablet.size(); i++) {
            MayTinhBang mtb = model.listTablet.get(i);

            if (code.equals(mtb.getCode())) {

                table_Tablet.setRowSelectionInterval(i, i);
                table_Tablet.scrollRectToVisible(
                        table_Tablet.getCellRect(i, 0, true)
                );

                JOptionPane.showMessageDialog(this,
                        "Tìm thấy sản phẩm:\n" + mtb,
                        "Tìm kiếm SP",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        JOptionPane.showMessageDialog(this,
                "Không tìm thấy SP nào với mã: " + code,
                "Tìm kiếm SP",
                JOptionPane.INFORMATION_MESSAGE);
    }

    public void sapXep() {
        model.listPhone.sort((a, b) -> Double.compare(b.getloiNhuan(), a.getloiNhuan()));
        model.listTablet.sort((a, b) -> Double.compare(b.getloiNhuan(), a.getloiNhuan()));

        DefaultTableModel tableModel_Phone = (DefaultTableModel) table_Phone.getModel();
        tableModel_Phone.setRowCount(0);

        DefaultTableModel tableModel_Tablet = (DefaultTableModel) table_Tablet.getModel();
        tableModel_Tablet.setRowCount(0);

        for (DienThoai dienThoai : model.listPhone) {
            showPhone(dienThoai);
        }
        for (MayTinhBang mayTinhBang : model.listTablet) {
            showTablet(mayTinhBang);
        }
    }
}
