/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controlller.QLRuongController;
import exection.KTKhongHopLeException;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.QLRuongModel;
import model.RuongHCN;
import model.RuongHinhVuong;


/**
 *
 * @author MyPC
 */
public class QLRuongView extends javax.swing.JFrame {

    public QLRuongModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLRuongView.class.getName());
    public ButtonGroup buttonGroup;

    /**
     * Creates new form QLRuongView
     */
    public QLRuongView() {

        initComponents();
        initView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ruong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_input_code = new javax.swing.JTextField();
        tf_inpur_own = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_inpur_caytronng = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_inpur_chieudai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_inpur_chieuRong = new javax.swing.JTextField();
        btn_ruong_saveFile = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        radioBtn_hcn = new javax.swing.JRadioButton();
        radioBtn_hv1 = new javax.swing.JRadioButton();
        btn_ruong_save1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_ruong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ruộng", "Chủ hộ", "Cây trồng", "Loại ruộng", "Chiều dài", "Chiều Rộng", "Diện Tích"
            }
        ));
        jScrollPane1.setViewportView(table_ruong);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 740, 280));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh Sách Ruộng Đất");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 320));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nhập Thông Tin Ruộng");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setText("Mã Ruộng");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel2.add(tf_input_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, -1));
        jPanel2.add(tf_inpur_own, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, -1));

        jLabel4.setText("Tên Chủ hộ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, -1));

        jLabel5.setText("Loại Cây Trồng");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));
        jPanel2.add(tf_inpur_caytronng, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, -1));

        jLabel6.setText("Chiều Dài");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, -1));
        jPanel2.add(tf_inpur_chieudai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, -1));

        jLabel7.setText("Chiều Rộng");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));
        jPanel2.add(tf_inpur_chieuRong, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 200, -1));

        btn_ruong_saveFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ruong_saveFile.setText("Lưu File");
        btn_ruong_saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruong_saveFileActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ruong_saveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 220, 130));

        jLabel8.setText("Loại rộng");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, -1));

        radioBtn_hcn.setText("Hình chữ nhật");
        jPanel2.add(radioBtn_hcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        radioBtn_hv1.setText("Hình Vuông");
        jPanel2.add(radioBtn_hv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        btn_ruong_save1.setText("Lưu");
        btn_ruong_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ruong_save1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ruong_save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 190, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 760, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ruong_saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruong_saveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ruong_saveFileActionPerformed

    private void btn_ruong_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ruong_save1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ruong_save1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLRuongView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_ruong_save1;
    public javax.swing.JButton btn_ruong_saveFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JRadioButton radioBtn_hcn;
    public javax.swing.JRadioButton radioBtn_hv1;
    public javax.swing.JTable table_ruong;
    public javax.swing.JTextField tf_inpur_caytronng;
    public javax.swing.JTextField tf_inpur_chieuRong;
    public javax.swing.JTextField tf_inpur_chieudai;
    public javax.swing.JTextField tf_inpur_own;
    public javax.swing.JTextField tf_input_code;
    // End of variables declaration//GEN-END:variables
    public void initView() {
        setTitle("Quan Ly Ruong Dat");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        ActionListener ac = new     QLRuongController(this);
        model = new QLRuongModel();

        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioBtn_hv1);
        buttonGroup.add(radioBtn_hcn);
        
        btn_ruong_save1.addActionListener(ac);
        btn_ruong_saveFile.addActionListener(ac);
        setVisible(true);
    }
    public void themRuongHV() throws KTKhongHopLeException{
        String maRuong = tf_input_code.getText();
        String chuHo = tf_inpur_own.getText();
        String loaiCayTrong = tf_inpur_caytronng.getText();
        double doDaiCanh = parseDoubleHV(tf_inpur_chieudai.getText(), tf_inpur_chieuRong.getText(), "Độ dài cạnh");
        
        RuongHinhVuong hinhVuong = new RuongHinhVuong(doDaiCanh, maRuong, chuHo, loaiCayTrong);
        model.addRuongHv(hinhVuong);
    }
    
    public void themRuongHCN() throws KTKhongHopLeException{
        String maRuong = tf_input_code.getText();
        String chuHo = tf_inpur_own.getText();
        String loaiCayTrong = tf_inpur_caytronng.getText();
        
        double chieuDai = parseDouble(tf_inpur_chieudai.getText(), "Chieu Dai");
        double chieuRong = parseDouble(tf_inpur_chieuRong.getText(), "Chieu Rong");
        
        RuongHCN hcn = new RuongHCN(chieuDai, chieuRong, maRuong, chuHo, loaiCayTrong);
        model.addRuongHcn(hcn);
    }
    
    public void showThongTin(){
        DefaultTableModel tableModel = (DefaultTableModel) table_ruong.getModel();
        
        tableModel.setRowCount(0);
        
        for (RuongHinhVuong ruongHinhVuong : model.listRuongHv) {
            tableModel.addRow(new Object[]{
                            ruongHinhVuong.getMaRuong(), 
                            ruongHinhVuong.getChuHo(), 
                            ruongHinhVuong.getLoaiCayTrong(), 
                            "Hình Vuông", 
                            ruongHinhVuong.getDoDaiCanh(), 
                            ruongHinhVuong.getDoDaiCanh(),
                            ruongHinhVuong.tinhDienTich()});
        }
        for (RuongHCN hcn : model.listRuongHcn) {
            tableModel.addRow(new Object[]{
                            hcn.getMaRuong(), 
                            hcn.getChuHo(), 
                            hcn.getLoaiCayTrong(), 
                            "Hình chữ nhật", 
                            hcn.getChieuDai(), 
                            hcn.getChieuRong(), 
                            hcn.tinhDienTich()});
        }
    }
    
    public void luuFile(String path){
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(path))){
            
            for (RuongHCN ruongHCN : model.listRuongHcn) {
                bw.write(ruongHCN.toString());
                bw.newLine();
            }
            
            for (RuongHinhVuong ruongHinhVuong : model.listRuongHv) {
                bw.write(ruongHinhVuong.toString());
                bw.newLine();
            }
            
            JOptionPane.showMessageDialog(this, "Da luu vao file " + path, "Da LUU", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "LOI File ???", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public double parseDouble(String input, String name) throws KTKhongHopLeException{
        if(input == null || input.trim().isEmpty()){
            throw new KTKhongHopLeException(name + " không được để trống kích thước");
        }
        try {
            double value = Double.parseDouble(input.trim());
            
            if(value <= 0) throw new KTKhongHopLeException(name + " có kích thước phải là số dương");
            
            return value;
        } catch (NumberFormatException e) {
            throw new KTKhongHopLeException(name + " phải là số");
        }
    }
    
    public double parseDoubleHV(String input1, String input2, String name) throws KTKhongHopLeException{
         if(input1 == null || input1.trim().isEmpty() || input2 == null || input2.trim().isEmpty()){
             throw new KTKhongHopLeException(name + " Không được để trống");
         }
         
         try {
            double value1 = Double.parseDouble(input1.trim());
            double value2 = Double.parseDouble(input2.trim());
            
            if (value1 <= 0 || value2 <= 0){
                throw new KTKhongHopLeException(name + " phải là số dương");
            }
            
            if (value1 != value2){
                throw new KTKhongHopLeException("Chiều dài và Chiều Rộng của hình vuông phải bằng nhau");
            }
            return value1;
        } catch (NumberFormatException e ) {
            throw new KTKhongHopLeException(name + " phải là số");
        }
    }
}
